lesson:
  limit: 20
category:
  image_mini_width: 60
  image_mini_height: 40
  image_width: 300
  image_height: 200
  default_image_path: "category/cat_category.jpg"
user:
  avatar_default_path: "user/avatar/cat.jpg"
  avatar_size: 50
  avatar_large_size: 100
  avatar_mini_size: 20
zero: 0
one: 1
two: 2
word_filter:
  - learned
  - not_learned
  - all_words
